//! Lookup tables: test names, fuel/air status strings, compliance
//! levels, fuel types and Mode 06 test IDs.
//!
//! The DTC table (2066 entries) is generated by `tools/specs-generator` into
//! `dtc_table.rs`; everything here is small and hand-ported.
//!
// SPDX-License-Identifier: GPL-3.0-or-later

/// Ignition type names, indexed by bit 12 of the Mode 01 PID 01 reply.
pub const IGNITION_TYPE: [&str; 2] = ["spark", "compression"];

/// The 3 base diagnostic tests always present in a PID 01 reply.
pub const BASE_TESTS: [&str; 3] = [
    "MISFIRE_MONITORING",
    "FUEL_SYSTEM_MONITORING",
    "COMPONENT_MONITORING",
];

/// Spark-ignition tests (byte 2 of the PID 01 reply).
///
/// `None` marks reserved bit positions, mirroring `SPARK_TESTS`.
pub const SPARK_TESTS: [Option<&str>; 8] = [
    Some("CATALYST_MONITORING"),
    Some("HEATED_CATALYST_MONITORING"),
    Some("EVAPORATIVE_SYSTEM_MONITORING"),
    Some("SECONDARY_AIR_SYSTEM_MONITORING"),
    None,
    Some("OXYGEN_SENSOR_MONITORING"),
    Some("OXYGEN_SENSOR_HEATER_MONITORING"),
    Some("EGR_VVT_SYSTEM_MONITORING"),
];

/// Compression-ignition tests (byte 2 of the PID 01 reply).
pub const COMPRESSION_TESTS: [Option<&str>; 8] = [
    Some("NMHC_CATALYST_MONITORING"),
    Some("NOX_SCR_AFTERTREATMENT_MONITORING"),
    None,
    Some("BOOST_PRESSURE_MONITORING"),
    None,
    Some("EXHAUST_GAS_SENSOR_MONITORING"),
    Some("PM_FILTER_MONITORING"),
    Some("EGR_VVT_SYSTEM_MONITORING"),
];

/// Fuel system status names, indexed by the byte value (bit position).
pub const FUEL_STATUS: [&str; 5] = [
    "Open loop due to insufficient engine temperature",
    "Closed loop, using oxygen sensor feedback to determine fuel mix",
    "Open loop due to engine load OR fuel cut due to deceleration",
    "Open loop due to system failure",
    "Closed loop, using at least one oxygen sensor but there is a fault in the feedback system",
];

/// Secondary air status names.
pub const AIR_STATUS: [&str; 4] = [
    "Upstream",
    "Downstream of catalytic converter",
    "From the outside atmosphere or off",
    "Pump commanded on for diagnostics",
];

/// OBD compliance strings, indexed by the PID 1C value.
pub const OBD_COMPLIANCE: [&str; 34] = [
    "Undefined",
    "OBD-II as defined by the CARB",
    "OBD as defined by the EPA",
    "OBD and OBD-II",
    "OBD-I",
    "Not OBD compliant",
    "EOBD (Europe)",
    "EOBD and OBD-II",
    "EOBD and OBD",
    "EOBD, OBD and OBD II",
    "JOBD (Japan)",
    "JOBD and OBD II",
    "JOBD and EOBD",
    "JOBD, EOBD, and OBD II",
    "Reserved",
    "Reserved",
    "Reserved",
    "Engine Manufacturer Diagnostics (EMD)",
    "Engine Manufacturer Diagnostics Enhanced (EMD+)",
    "Heavy Duty On-Board Diagnostics (Child/Partial) (HD OBD-C)",
    "Heavy Duty On-Board Diagnostics (HD OBD)",
    "World Wide Harmonized OBD (WWH OBD)",
    "Reserved",
    "Heavy Duty Euro OBD Stage I without NOx control (HD EOBD-I)",
    "Heavy Duty Euro OBD Stage I with NOx control (HD EOBD-I N)",
    "Heavy Duty Euro OBD Stage II without NOx control (HD EOBD-II)",
    "Heavy Duty Euro OBD Stage II with NOx control (HD EOBD-II N)",
    "Reserved",
    "Brazil OBD Phase 1 (OBDBr-1)",
    "Brazil OBD Phase 2 (OBDBr-2)",
    "Korean OBD (KOBD)",
    "India OBD I (IOBD I)",
    "India OBD II (IOBD II)",
    "Heavy Duty Euro OBD Stage VI (HD EOBD-IV)",
];

/// Fuel type names, indexed by the PID 51 value.
pub const FUEL_TYPES: [&str; 24] = [
    "Not available",
    "Gasoline",
    "Methanol",
    "Ethanol",
    "Diesel",
    "LPG",
    "CNG",
    "Propane",
    "Electric",
    "Bifuel running Gasoline",
    "Bifuel running Methanol",
    "Bifuel running Ethanol",
    "Bifuel running LPG",
    "Bifuel running CNG",
    "Bifuel running Propane",
    "Bifuel running Electricity",
    "Bifuel running electric and combustion engine",
    "Hybrid gasoline",
    "Hybrid Ethanol",
    "Hybrid Diesel",
    "Hybrid Electric",
    "Hybrid running electric and combustion engine",
    "Hybrid Regenerative",
    "Bifuel running diesel",
];

/// Mode 06 test IDs: `<TID>` -> `(<name>, <description>)`.
pub const TEST_IDS: [(u8, &str, &str); 12] = [
    (
        0x01,
        "RTL_THRESHOLD_VOLTAGE",
        "Rich to lean sensor threshold voltage",
    ),
    (
        0x02,
        "LTR_THRESHOLD_VOLTAGE",
        "Lean to rich sensor threshold voltage",
    ),
    (
        0x03,
        "LOW_VOLTAGE_SWITCH_TIME",
        "Low sensor voltage for switch time calculation",
    ),
    (
        0x04,
        "HIGH_VOLTAGE_SWITCH_TIME",
        "High sensor voltage for switch time calculation",
    ),
    (0x05, "RTL_SWITCH_TIME", "Rich to lean sensor switch time"),
    (0x06, "LTR_SWITCH_TIME", "Lean to rich sensor switch time"),
    (0x07, "MIN_VOLTAGE", "Minimum sensor voltage for test cycle"),
    (0x08, "MAX_VOLTAGE", "Maximum sensor voltage for test cycle"),
    (0x09, "TRANSITION_TIME", "Time between sensor transitions"),
    (0x0A, "SENSOR_PERIOD", "Sensor period"),
    (
        0x0B,
        "MISFIRE_AVERAGE",
        "Average misfire counts for last ten driving cycles",
    ),
    (
        0x0C,
        "MISFIRE_COUNT",
        "Misfire counts for last/current driving cycles",
    ),
];

/// Looks up a Mode 06 test ID, returning `(name, description)`.
pub fn test_id(tid: u8) -> Option<(&'static str, &'static str)> {
    TEST_IDS
        .iter()
        .find(|(id, _, _)| *id == tid)
        .map(|(_, name, desc)| (*name, *desc))
}
